version: '3.8'

services:
  web:
    build:
      context: ./web
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION-6.4}
        PROJECT: ${PROJECT-my_project}
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/html/${PROJECT-my_project}
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: "${PROJECT-my_project}_db"
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
