services:
  web:
    build:
      context: ./web
    ports:
      - "80:80"
    volumes:
      - ./symfony:/var/www/html/demo 
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: "demo_db"
      MARIADB_USER: symfony
      MARIADB_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
